### ISSUE TITLE
installing v4l2camera node module error

### ISSUE THREAD

**Issue by karthikbnd** [bellbind/node-v4l2camera#20]
reply@ubuntu:~/Desktop/node_modules$ sudo npm install v4l2camera
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported

> v4l2camera@1.0.2 install /home/reply/Desktop/node_modules/v4l2camera
> node-gyp rebuild

make: Entering directory `/home/reply/Desktop/node_modules/v4l2camera/build'
  CC(target) Release/obj.target/v4l2camera/capture.o
  CXX(target) Release/obj.target/v4l2camera/v4l2camera.o
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [Release/obj.target/v4l2camera/v4l2camera.o] Error 1
make: Leaving directory `/home/reply/Desktop/node_modules/v4l2camera/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/reply/Desktop/node_modules/v4l2camera
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open '/home/reply/Desktop/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/home/reply/Desktop/node_modules/build/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/home/reply/Desktop/node_modules/frames/package.json'
npm WARN EPACKAGEJSON Desktop No description
npm WARN EPACKAGEJSON Desktop No repository field.
npm WARN EPACKAGEJSON Desktop No README data
npm WARN EPACKAGEJSON Desktop No license field.
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "v4l2camera"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! v4l2camera@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v4l2camera@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v4l2camera package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls v4l2camera
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/reply/Desktop/node_modules/npm-debug.log

**Comment by karthikbnd** [comment]
solved with the prerequisites installation
The error is due to gcc version
